### ISSUE TITLE
Consider use relative css path

### ISSUE THREAD

**Issue by mgurg** [janraasch/hugo-product-launch#160]
I started using Hugo today, this is the first template I tested.

According to readme: 
> Simply copy over the contents of the exampleSite-directory included in this theme

Static site (in public folder) build in this way has broken CSS link (starts from http://examplesite.com/...) I solved this by using relative path in styling.html file:

`<link href=".{{ $css.RelPermalink }}" rel="stylesheet" />`

I think that could be helpful for beginners :)

**Comment by janraasch** [comment]
Hi @mgurg, thank you. These path(s) config are causing problems for many »new-comers« - I think 👍. Usually the problem then is a misconfigured `baseURL`-param. It looks like you did not adjust / edit the `config.toml` to after copying over the files, see https://github.com/janraasch/hugo-product-launch/blob/master/exampleSite/config.toml#L1.
