### ISSUE TITLE
Enable »nocode« custom colors

### ISSUE THREAD

**Issue by janraasch** [janraasch/hugo-product-launch#2]
# Goal

Enable anybody to change the default colors of this theme without having to understand file formatting or CSS.

# Idea

Provide access to custom colors as outlined in https://github.com/janraasch/hugo-product-launch/blob/master/assets/css/main.css via a `colors.yml`-file which may be conveniently edited via https://forestry.io/docs/settings/fields/color-picker/. Depends on https://github.com/janraasch/hugo-product-launch/issues/1.

**Comment by janraasch** [comment]
See https://github.com/janraasch/hugo-product-launch/tree/test-usage-of-variables-on-main-css for a first test 🥇 😄 .

**Comment by micklynch** [comment]
This would be a nice feature...I'd like to give it a `+1`

**Comment by janraasch** [comment]
Hi @micklynch, thank you for the feedback 🥇. I was hoping somebody would pick up one this 😍.

---

`#offtopic` Are you using this theme already? I'd love to see your use case.
