### ISSUE TITLE
Hugo rendering does not work as expected

### ISSUE THREAD

**Issue by maxkratz** [janraasch/hugo-product-launch#30]
Hello,

I've followed your guide to setup the example site for testing. If I start `hugo server` everything is fine and I get a css file with several thousand lines.

But if I render the page with `hugo`, the css is incomplete:

- Its name is not `main.css` -> It is something like `main.ec19971888d6d03ee7354d70b3b1b70cc3cf5ee8e7c34f98ddedd7348dd4c32b.css`
- Its content is incomplete.
- The webpage clearly shows that css is missing something:

![Bildschirmfoto_2020-11-10_14-55-27](https://user-images.githubusercontent.com/20956405/98682963-cc867e00-2364-11eb-9dcf-01f8695fe85d.png)

I am using hugo version 0.74.3 and npm 6.14.8. Am I missing something?

**Comment by janraasch** [comment]
Hi @maxkratz,

thank you for getting in touch 🙌 😃.

> Am I missing something?

It sure looks like it 😉. Let's try to find out what exactly it is you are missing 🙂:

**Did you clone the kickstart-repo https://github.com/janraasch/hugo-product-launch-kickstart ?**

I think that is probably the easiest way to make sure you have all the files in all the right places. Otherwise could you send me the contents of your site's directory, i.e. the result of running `ls -la` if your on linux / mac.

Have a good one 👋,
Jan

**Comment by maxkratz** [comment]
Thank you for helping me out :)

> Did you clone the kickstart-repo https://github.com/janraasch/hugo-product-launch-kickstart ?
> I think that is probably the easiest way to make sure you have all the files in all the right places.

What I've done so far:
* `$ git clone https://github.com/janraasch/hugo-product-launch-kickstart.git`
* `$ cd hugo-product-launch-kickstart`
* `$ git submodule update --init --recursive`
* `$ npm install`
* `$ sudo npm install postcss-cli postcss -g`
* `$ hugo`

But rendering of the kickstart project does not work for me, either ... (`hugo server` sucessfully builds the page and serves it correctly!)

Output of `ls -la`:
```
 maxkratz@thinkbrett ~/Schreibtisch/hugo-product-launch-kickstart $ ls -la        
insgesamt 280
drwxrwxr-x  14 maxkratz maxkratz  4096 Nov 11 13:39 .
drwxr-xr-x   9 maxkratz maxkratz 28672 Nov 11 13:37 ..
drwxrwxr-x   3 maxkratz maxkratz  4096 Nov 11 13:37 assets
drwxrwxr-x   3 maxkratz maxkratz  4096 Nov 11 13:37 config
-rw-rw-r--   1 maxkratz maxkratz  2389 Nov 11 13:37 config.toml
drwxrwxr-x   2 maxkratz maxkratz  4096 Nov 11 13:37 content
drwxrwxr-x   3 maxkratz maxkratz  4096 Nov 11 13:37 .forestry
drwxrwxr-x   9 maxkratz maxkratz  4096 Nov 11 13:38 .git
drwxrwxr-x   2 maxkratz maxkratz  4096 Nov 11 13:37 .github
-rw-rw-r--   1 maxkratz maxkratz    39 Nov 11 13:37 .gitignore
-rw-rw-r--   1 maxkratz maxkratz   136 Nov 11 13:37 .gitmodules
-rw-rw-r--   1 maxkratz maxkratz  2638 Nov 11 13:39 hugo_stats.json
-rw-rw-r--   1 maxkratz maxkratz   467 Nov 11 13:37 netlify.toml
drwxrwxr-x 149 maxkratz maxkratz 24576 Nov 11 13:39 node_modules
-rw-rw-r--   1 maxkratz maxkratz  1103 Nov 11 13:37 package.json
-rw-rw-r--   1 maxkratz maxkratz 70231 Nov 11 13:37 package-lock.json
drwxr-xr-x   4 maxkratz maxkratz  4096 Nov 11 13:39 public
-rw-rw-r--   1 maxkratz maxkratz  3222 Nov 11 13:37 README.md
drwxrwxr-x   3 maxkratz maxkratz  4096 Nov 11 13:37 resources
drwxrwxr-x   2 maxkratz maxkratz  4096 Nov 11 13:37 scripts
drwxrwxr-x   3 maxkratz maxkratz  4096 Nov 11 13:37 static
-rw-rw-r--   1 maxkratz maxkratz   269 Nov 11 13:37 tailwind.config.js
drwxrwxr-x   3 maxkratz maxkratz  4096 Nov 11 13:37 themes
```

Thank you again for your help!

**Comment by janraasch** [comment]
Hi @maxkratz, I think this might be a *witch hunt*. 

Could it be that you try to a access the `public/index.html`-file via the `file:///`-protocol in your browser? Your screenshot does not show the `url` in the browser but I suspect it starts with `file:///`. **Am I correct?**

If so, then everything is fine and there actually is no problem at all. It's just that the production build of a hugo generated site is meant to be served via a webserver (i.e. `http://` or `https://`). Usually one would not look at the production build via the local filesystem, but push it to a webserver to be served via nginx or something like netlify.

**Comment by maxkratz** [comment]
Hey @janraasch! I think I resolved it :).

> Could it be that you try to a access the public/index.html-file via the file:///-protocol in your browser? Your screenshot does not show the url in the browser but I suspect it starts with file:///. Am I correct?

I've used a local docker container with nginx to serve the files so my url started with 'http://'.

My error was another: I've missed the file `config/production/build.toml`. Without this file, hugo wasn't able to build proper CSS and I thought that it is just for activating some statistic output. After I added the file to my personal site (and the example site ...), all hugo builds work just fine. My bad!

Maybe you can add this dependency to your readme into the section with all copy instructions for `package.json` etc.

Thanks again for your help! I'll close this issue now :heart:.
