### ISSUE TITLE
hugo-product-launch-kickstart - starting point ?

### ISSUE THREAD

**Issue by nyue** [janraasch/hugo-product-launch#92]
I am trying out https://github.com/janraasch/hugo-product-launch-kickstart, is this example meant to work out of the box just running

```
hugo server
```

I am getting the following errors so I am not sure if this example requires additional customisation before it will work

```
Start building sites … 
Built in 12 ms
Error: Error building site: "/data1/nyue/temp/hugo/hugo-product-launch-kickstart/content/_index.md:21:1": failed to extract shortcode: template for shortcode "contact_form" not found
```

Cheers

**Comment by janraasch** [comment]
Hi @nyue, thank you for getting in touch 🤝 😁.

It looks like you have not checked out the `themes/hugo-product-launch`-directory. The theme is a `git-submodule`.

I assume you `git clone`d `hugo-product-launch-kickstart`. To initialize & check out the submodule, you could run

```
git submodule update --init
```

I hope that helps 🙏.

Let me know, if you have any other/follow-up questions 🤓.

Cheers 👋🏻 ,
Jan

**Comment by nyue** [comment]
That works. Thank you.
